### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by JanCizmar** [hamzasaleem2/sticky#4]
Hello!

I found your project on Reddit and I would like to contribute by adding i18n using Tolgee to your project.

Can you please guide me, what's the simplest way to run the frontend locally?

When I run it, I get: 

```
client.ts:258 Uncaught Error: Provided address was not an absolute URL.
    at new ConvexReactClient (client.ts:258:13)
    at main.tsx:14:16
```

Can I connect my frontend to the production backend somehow?

Thanks!

**Comment by hamzasaleem2** [comment]
@JanCizmar thank you for checking sticky.today out.

Here's the guide to host it yourself.
https://kaput-seaplane-9ca.notion.site/Sticky-Self-Hosting-Guide-067095a6cb5d445c87e9616ea2ebea61

You'll need to spin up your own instance on convex.dev and clerk. No paid subscription required.

**Comment by JanCizmar** [comment]
Hey! Thanks for the guide. Isn't there some easier way without creating the accounts in third party services? I really just need to run the frontend, so I might be able to use the production backend.
